<?php
return [
    'products' => [
        'table' => 'products',
        'form'    => 'prodform',
        'list'    => 'prodlist',
        'fields'  => ['slug', 'title', 'cat_id'],
        'headers' => ['Row', 'Title', 'Slug', 'Active', 'View/Edit', 'Delete'],
        'columns' => [
            ['type' => 'counter'],
            ['type' => 'editfield', 'field' => 'title', 'mode' => 'pn', 'width' => '200px'],
            ['type' => 'text',      'field' => 'slug', 'width' => '150px'], 
            ['type' => 'flip',      'field' => 'active',  'center' => true],
            ['type' => 'action',    'target' => 'edit',   'center' => true],
            ['type' => 'action',    'target' => 'delete', 'center' => true],
        ],
    ],
    'events' => [
        'table' => 'events',
        'form'    => 'eventform',
        'list'    => 'eventlist',
        'fields'  => ['slug', 'title', 'cat_id'],
        'headers' => ['Row', 'Title', 'Slug', 'Active', 'View/Edit', 'Delete'],
        'columns' => [
            ['type' => 'counter'],
            ['type' => 'editfield', 'field' => 'title', 'mode' => 'pn', 'width' => '200px'],
            ['type' => 'text',      'field' => 'slug', 'width' => '150px'], 
            ['type' => 'flip',      'field' => 'active',  'center' => true],
            ['type' => 'action',    'target' => 'edit',   'center' => true],
            ['type' => 'action',    'target' => 'delete', 'center' => true],
        ],
    ],
    'pages' => [
        'table'   => 'pages',
        'form'    => 'pageform',
        'list'    => 'pagelist',
        'fields'  => ['title', 'slug'],
        'headers' => ['ID', 'Title', 'Slug', 'Active', 'View/Edit', 'Delete'],
        'columns' => [
            ['type' => 'text',      'field' => 'id'],
            ['type' => 'editfield', 'field' => 'title', 'mode' => 'pn', 'width' => '200px'],
            ['type' => 'text',      'field' => 'slug', 'width' => '150px'], 
            ['type' => 'flip',      'field' => 'active',  'center' => true],
            ['type' => 'action',    'target' => 'edit',   'center' => true],
            ['type' => 'action',    'target' => 'delete', 'center' => true],
        ],
    ],
    'navigation' => [
        'table'   => 'navigation',
        'form'    => 'navform',
        'list'    => 'navlist',
        'fields'  => ['label', 'slug'],
        'headers' => ['ID', 'Label', 'Slug', 'Active', 'View/Edit', 'Delete'],
        'columns' => [
            ['type' => 'text',      'field' => 'id'],
            ['type' => 'editfield', 'field' => 'label', 'mode' => 'pn', 'width' => '200px'],
            ['type' => 'text',      'field' => 'slug', 'width' => '150px'], 
            ['type' => 'flip',      'field' => 'active',  'center' => true],
            ['type' => 'action',    'target' => 'edit',   'center' => true],
            ['type' => 'action',    'target' => 'delete', 'center' => true],
        ],
    ],    
];